Handle GetConnectedDeviceSync failures correctly (#18802)
* Handle GetConnectedDeviceSync failures correctly

Currently a failure to GetConnectedDeviceSync causes an exception
NameError: name 'CHIP_ERROR_INTERNAL' is not defined.

Handle the error case correctly and throw an exception in the main
context. Also make ResolveNode more pythonic by not using a return
value but letting the Exception bubble up.

* Address ResolveNode API change

Handle ChipStackError exception instead of checking the return value.