Rearrange code in InetInterface (#10502)
#### Problem

Code for different Inet implementations is scattered across many `#if`s.

#### Change overview

- Groups code by implementation.
- Moves doxygen comments to the header.

Since comparing moved code in diff format is difficult, this change
explicitly does NOT make any changes to function bodies, with one
exception: incorporating the CloseIOSocket() bug fix from PR#10452
to avoid conflicts.

This is a step toward #7715 _Virtualize System and Inet interfaces_.

#### Testing

CI; no change to functionality.