Add Chef rootnode_fan as sample device (#22629)
* Add Chef rootnode_fan as sample device

Add Chef rootnode_fan as sample device
including .zap / .matter / zzz-generated files

* Clear invalid array default value from ZAP

* The `SupportedLocales` which has `en-US` as default value is invalid
because it is Array type.
* `DefaultOtaProviders` containing default value 0 is also cleared
* Regenerate *.matter file from modified ZAP file

* Fix lint reported error

ERROR: Required attributes: EP0:AccessControl does not expose SubjectsPerAccessControlEntry(2)
	attribute at ./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1343:3
ERROR: Required attributes: EP0:AccessControl does not expose TargetsPerAccessControlEntry(3)
	attribute at ./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1343:3
ERROR: Required attributes: EP0:AccessControl does not expose AccessControlEntriesPerFabric(4)
	attribute at ./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1343:3
ERROR: Required attributes: EP0:Basic does not expose CapabilityMinima(19) attribute at
	./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1351:3
ERROR: Required attributes: EP0:LocalizationConfiguration does not expose ActiveLocale(0)
	attribute at ./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1384:3
ERROR: Required attributes: EP0:GeneralCommissioning does not expose SupportsConcurrentConnection(4)
	attribute at ./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1398:3
ERROR: Required attributes: EP0:Switch does not expose number of positions(0) attribute
	at ./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1548:3
ERROR: Required attributes: EP0:Switch does not expose current position(1) attribute
	at ./examples/chef/devices/rootnode_fan_7N2TobIlOX.matter:1548:3

Co-authored-by: Andrei Litvin <andy314@gmail.com>