Fix include checking for src/include/platform/internal/*.cpp (#15121)
Since these .cpp files are included instead of being listed in sources,
they are not processed by the include checker. This has allowed the
introduction of a dependency cycle in

  1e8ed9de5 ("Updated Device to Get PASE Verifier from Memory. (#14676)")

which in turn result in the following build flake:

  FAILED: obj/src/platform/Darwin/Darwin.ConfigurationManagerImpl.cpp.o
  g++ -MMD -MF obj/src/platform/Darwin/Darwin.ConfigurationManagerImpl.cpp.o.d -target x86_64-apple-macos10.15 -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow -Wunreachable-code -Wvla -Wformat -Wformat-nonliteral -Wformat-security -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wno-cast-function-type -fno-strict-aliasing -target x86_64-apple-macos10.15 -arch arm64 -arch x86_64 -fobjc-arc -std=gnu++14 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -I../../../../../../../../src/include -I../../../../../../../../src -Igen/include -I../../../../../../../../zzz_generated/app-common -I../../../../../../../../config/standalone -I../../../../../../../../third_party/nlassert/repo/include -I../../../../../../../../third_party/nlio/repo/include -I../../../../../../../../third_party/mbedtls/repo/include -c ../../../../../../../../src/platform/Darwin/ConfigurationManagerImpl.cpp -o obj/src/platform/Darwin/Darwin.ConfigurationManagerImpl.cpp.o
  In file included from ../../../../../../../../src/platform/Darwin/ConfigurationManagerImpl.cpp:31:
  In file included from ../../../../../../../../src/include/platform/internal/GenericConfigurationManagerImpl.cpp:38:
  In file included from ../../../../../../../../src/protocols/secure_channel/PASESession.h:34:
  In file included from ../../../../../../../../src/messaging/ExchangeContext.h:31:
  In file included from ../../../../../../../../src/messaging/ExchangeDelegate.h:27:
  In file included from ../../../../../../../../src/messaging/ApplicationExchangeDispatch.h:28:
  In file included from ../../../../../../../../src/messaging/ExchangeMessageDispatch.h:27:
  In file included from ../../../../../../../../src/transport/SessionManager.h:39:
  In file included from ../../../../../../../../src/transport/GroupSession.h:22:
  In file included from ../../../../../../../../src/transport/Session.h:19:
  In file included from ../../../../../../../../src/credentials/FabricTable.h:27:
  In file included from ../../../../../../../../src/credentials/CHIPCert.h:34:
  ../../../../../../../../src/lib/asn1/ASN1.h:30:10: fatal error: 'asn1/ASN1OID.h' file not found
  #include <asn1/ASN1OID.h>
           ^~~~~~~~~~~~~~~~
  1 error generated.

The requisite dependency for this include cannot be added, because it
results in a cycle:

  ERROR Dependency cycle:
    //src/platform:platform ->
    //src/protocols/secure_channel:secure_channel ->
    //src/messaging:messaging ->
    //src/platform:platform

Fix the diagnostic so that dependency errors in these files are caught:

  ERROR at //src/include/platform/internal/GenericConfigurationManagerImpl.ipp:38:11: Include not allowed.
  #include <protocols/secure_channel/PASESession.h>
	    ^-------------------------------------
  It is not in any dependency of
    //src/platform:platform
  The include file is in the target(s):
    //src/protocols/secure_channel:secure_channel
  which should somehow be reachable.