Add missing <inttypes.h> include (#4419)
This fixes the following compile error on some systems:

src/app/server/QRCodeUtil.cpp:42:55:
error: expected ')'
        ChipLogProgress(AppServer, "SetupPINCode: [%" PRIu32 "]",
	setupPinCode);