Shutdown Python REPL correctly (#18437)
* Python REPL: Shutdown CHIP stack properly

* Make sure Storage is deallocated before ChipStack is Shutdown

Otherwise, we later fail to access the builtins.chipStack:
AttributeError: module 'builtins' has no attribute 'chipStack'

* Add comment why we need to explictily set _persistentStorage to None