Add CONFIG_MBEDTLS_HKDF_C=y to some esp32 defaults. (#26750)
This seems to be required, otherwise I get errors like:

```
config/esp32/third_party/connectedhomeip/src/crypto/CHIPCryptoPALmbedTLS.cpp:330: undefined reference to `mbedtls_hkdf'
```

Co-authored-by: Andrei Litvin <andreilitvin@google.com>