GN: Add OpenThread support to nRF5 examples (#2045)
* Fix buttons handling crash in nRF5 samples

Best not to jump to a random address for unhandled buttons.

* Rename OpenThread configs to new names

Fixes the following errors:

error: #error "OPENTHREAD_CONFIG_MAX_TX_ATTEMPTS_INDIRECT_POLLS was
replaced by OPENTHREAD_CONFIG_MAC_MAX_TX_ATTEMPTS_INDIRECT_POLLS."
  223 | #error \
      |  ^~~~~

etc.

* Add the options from configure.ac to OpenThreadConfig.h

* Conditionally compile endpoints

These files don't compile correctly if disabled. Add the conditions to
make e.g. chip_inet_config_enable_raw_endpoint=false compile.

* Deduplicate args.gni for nRF5 examples

Move common args between lock-app and lighting-app to
examples/platform/nrf528xx/args.gni.

Also make some minor build file cleanups.

* GN: Add OpenThread support to nRF5 examples

Bring up Thread support in the nRF5 example applications. This adds a
bulid file for the OpenThread nrf528xx platform that uses the installed
SDK instead of the one checked into OpenThread. Using multiple SDK
versions in the build does not seem safe.

Fixes #1516

Depends on #2044, #2036, #2034, #2032

* Restyled by clang-format

* Update OpenThread

* Update .gitmodules

Co-authored-by: Restyled.io <commits@restyled.io>